# Generated by Django 4.2.26 on 2025-12-01 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], max_length=20)),
                ('form_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geoform_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('form_data', models.JSONField(default=dict)),
                ('points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collected_geodata', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_mobile_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_geo_data', to='admin_api.project', to_field='mobile_id')),
            ],
            options={
                'db_table': 'geoform_geodata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('export', 'Export'), ('filter', 'Filter'), ('search', 'Search')], max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
